fields:
-   metadata: {}
    name: WorkOrderID
    nullable: true
    type: integer
-   metadata: {}
    name: ProductID
    nullable: true
    type: integer
-   metadata: {}
    name: OrderQty
    nullable: true
    type: integer
-   metadata: {}
    name: StockedQty
    nullable: true
    type: integer
-   metadata: {}
    name: ScrappedQty
    nullable: true
    type: integer
-   metadata: {}
    name: StartDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: EndDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: DueDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: ScrapReasonID
    nullable: true
    type: integer
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
type: struct
