fields:
-   metadata: {}
    name: TransactionID
    nullable: true
    type: integer
-   metadata: {}
    name: ProductID
    nullable: true
    type: integer
-   metadata: {}
    name: ReferenceOrderID
    nullable: true
    type: integer
-   metadata: {}
    name: ReferenceOrderLineID
    nullable: true
    type: integer
-   metadata: {}
    name: TransactionDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: TransactionType
    nullable: true
    type: string
-   metadata: {}
    name: Quantity
    nullable: true
    type: integer
-   metadata: {}
    name: ActualCost
    nullable: true
    type: double
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
type: struct
