fields:
-   metadata: {}
    name: DocumentNode
    nullable: true
    type: string
-   metadata: {}
    name: DocumentLevel
    nullable: true
    type: integer
-   metadata: {}
    name: Title
    nullable: true
    type: string
-   metadata: {}
    name: Owner
    nullable: true
    type: integer
-   metadata: {}
    name: FolderFlag
    nullable: true
    type: boolean
-   metadata: {}
    name: FileName
    nullable: true
    type: string
-   metadata: {}
    name: FileExtension
    nullable: true
    type: string
-   metadata: {}
    name: Revision
    nullable: true
    type: double
-   metadata: {}
    name: ChangeNumber
    nullable: true
    type: integer
-   metadata: {}
    name: Status
    nullable: true
    type: integer
-   metadata: {}
    name: DocumentSummary
    nullable: true
    type: string
-   metadata: {}
    name: Document
    nullable: true
    type: string
-   metadata: {}
    name: rowguid
    nullable: true
    type: string
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
type: struct
