fields:
-   metadata: {}
    name: ProductModelID
    nullable: true
    type: string
-   metadata: {}
    name: Name
    nullable: true
    type: string
-   metadata: {}
    name: CatalogDescription
    nullable: true
    type: string
-   metadata: {}
    name: Instructions
    nullable: true
    type: string
-   metadata: {}
    name: rowguid
    nullable: true
    type: string
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
type: struct
