fields:
-   metadata: {}
    name: ProductID
    nullable: true
    type: integer
-   metadata: {}
    name: Name
    nullable: true
    type: string
-   metadata: {}
    name: ProductNumber
    nullable: true
    type: string
-   metadata: {}
    name: MakeFlag
    nullable: true
    type: boolean
-   metadata: {}
    name: FinishedGoodsFlag
    nullable: true
    type: boolean
-   metadata: {}
    name: Color
    nullable: true
    type: string
-   metadata: {}
    name: SafetyStockLevel
    nullable: true
    type: integer
-   metadata: {}
    name: ReorderPoint
    nullable: true
    type: integer
-   metadata: {}
    name: StandardCost
    nullable: true
    type: double
-   metadata: {}
    name: ListPrice
    nullable: true
    type: double
-   metadata: {}
    name: Size
    nullable: true
    type: string
-   metadata: {}
    name: SizeUnitMeasureCode
    nullable: true
    type: string
-   metadata: {}
    name: WeightUnitMeasureCode
    nullable: true
    type: string
-   metadata: {}
    name: Weight
    nullable: true
    type: double
-   metadata: {}
    name: DaysToManufacture
    nullable: true
    type: integer
-   metadata: {}
    name: ProductLine
    nullable: true
    type: string
-   metadata: {}
    name: Class
    nullable: true
    type: string
-   metadata: {}
    name: Style
    nullable: true
    type: string
-   metadata: {}
    name: ProductSubcategoryID
    nullable: true
    type: integer
-   metadata: {}
    name: ProductModelID
    nullable: true
    type: integer
-   metadata: {}
    name: SellStartDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: SellEndDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: DiscontinuedDate
    nullable: true
    type: string
-   metadata: {}
    name: rowguid
    nullable: true
    type: string
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
type: struct
