fields:
-   metadata: {}
    name: WorkOrderID
    nullable: true
    type: integer
-   metadata: {}
    name: ProductID
    nullable: true
    type: integer
-   metadata: {}
    name: OperationSequence
    nullable: true
    type: integer
-   metadata: {}
    name: LocationID
    nullable: true
    type: integer
-   metadata: {}
    name: ScheduledStartDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: ScheduledEndDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: ActualStartDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: ActualEndDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: ActualResourceHrs
    nullable: true
    type: double
-   metadata: {}
    name: PlannedCost
    nullable: true
    type: double
-   metadata: {}
    name: ActualCost
    nullable: true
    type: double
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
type: struct
