fields:
-   metadata: {}
    name: CultureID
    nullable: true
    type: string
-   metadata: {}
    name: Name
    nullable: true
    type: string
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
type: struct
