fields:
-   metadata: {}
    name: ProductID
    nullable: true
    type: integer
-   metadata: {}
    name: StartDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: EndDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: StandardCost
    nullable: true
    type: double
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
type: struct
