fields:
-   metadata: {}
    name: IllustrationID
    nullable: true
    type: integer
-   metadata: {}
    name: Diagram
    nullable: true
    type: string
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
type: struct
