fields:
-   metadata: {}
    name: BillOfMaterialsID
    nullable: true
    type: integer
-   metadata: {}
    name: ProductAssemblyID
    nullable: true
    type: integer
-   metadata: {}
    name: ComponentID
    nullable: true
    type: integer
-   metadata: {}
    name: StartDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: EndDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: UnitMeasureCode
    nullable: true
    type: string
-   metadata: {}
    name: BOMLevel
    nullable: true
    type: integer
-   metadata: {}
    name: PerAssemblyQty
    nullable: true
    type: double
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
type: struct
