trigger:
  branches:
    include:
    - main
  paths:
    include:
    - ad_works_dw

pool:
  vmImage: 'ubuntu-latest'

# strategy:
#   matrix:
#     Python38:
#       python.version: '3.8'

stages:
  - stage: devevlopmentDeployment
    displayName: Deploy dbx notebooks to Dev
    variables:
      - group: development


    jobs:
      - deployment: deployAdWorksDWNotebooks
        displayName: Deploy ad_works_dw Notebooks
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/notebook.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceSubDirs: '$(DATABRICKS_WORKSPACE_SUBDIRS)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    FromWorkspaceDir: 'ad_works_dw'
                    ToWorkspaceDir: 'ad_works_dw'

      - deployment: deployAdWorksDWWorkflows
        displayName: Deploy ad_works_dw Workflows
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/workflows.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    SubDir: 'ad_works_dw/databricks/workflows'
